server:
  port: 8769
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign
