server:
  port: 8769
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/
spring:
  application:
    name: service-zuul
  http:
    multipart:
      enabled: true
      max-file-size: 10Mb
      max-request-size: 10Mb


zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign
